### ISSUE TITLE
Mimic `dotenv` API

### ISSUE THREAD

**Issue by piranna** [chmln/dotenv-toml#1]
Although similar, API of `dotenv-toml` is not the same as `dotenv`, but with some tune-ups would make them compatible and interchangeable. Problem is that the changes would break backward compatibility. Do you mind to review a pull-request?

**Comment by chmln** [comment]
@piranna sounds good! go ahead and make a PR

**Comment by piranna** [comment]
https://github.com/chmln/dotenv-toml/pull/2

Here you are :-) Don't doubt give me any comments :-)
